var districts = [{name: "Blekinge Fotbollsförbund",  id: 2},
                 {name: "Bohusläns Fotbollsförbund", id: 25},
                 {name: "Dalarnas FF",  id: 4},
                 {name: "Dalslands FF", id: 3},
                 {name: "Gestriklands FF", id: 6},
                 {name: "Gotlands FF",  id: 5},
                 {name: "Göteborgs FF", id: 7},
                 {name: "Hallands FF", id: 8},
                 {name: "Hälsinglands FF", id: 9},
                 {name: "Jämtland-Härjedalens FF", id: 10},
                 {name: "Medelpads FF", id: 11},
                 {name: "Norrbottens FF", id: 12},
                 {name: "Skånes FF", id: 14},
                 {name: "Smålands FF", id: 15},
                 {name: "Stockholms FF", id: 16},
                 {name: "SvFF", id: 1},
                 {name: "Södermanlands FF", id: 17},
                 {name: "Upplands FF", id: 18},
                 {name: "Värmlands FF", id: 19},
                 {name: "Västerbottens FF", id: 20},
                 {name: "Västergötlands FF", id: 21},
                 {name: "Västmanlands FF", id: 22},
                 {name: "Ångermanlands FF", id: 23},
                 {name: "Örebro Läns FF", id: 13},
                 {name: "Östergötlands FF", id: 24},
                 {name: "FIFA", id: 27}];

var venues = [{
	id: "309",
	name: "Tegstunets IP",
	lat: 63.814620, 
	lon: 20.243208,
	games: []
}];